name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Check clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --all-features

    - name: Run doc tests
      run: cargo test --doc

    - name: Set up integration test environment
      run: |
        # Create test private key file from secret
        echo "${{ secrets.OPEN_PAYMENTS_PRIVATE_KEY_CONTENT }}" > private.key
        chmod 600 private.key
        
        # Create .env file with all env vars
        echo "OPEN_PAYMENTS_SERVER_URL=${{ secrets.OPEN_PAYMENTS_SERVER_URL }}" >> .env
        echo "OPEN_PAYMENTS_WALLET_ADDRESS=${{ secrets.OPEN_PAYMENTS_WALLET_ADDRESS }}" >> .env
        echo "OPEN_PAYMENTS_KEY_ID=${{ secrets.OPEN_PAYMENTS_KEY_ID }}" >> .env
        echo "OPEN_PAYMENTS_PRIVATE_KEY_PATH=./private.key" >> .env

    - name: Run integration tests
      run: cargo test --test integration --all-features
      env:
        OPEN_PAYMENTS_SERVER_URL: ${{ secrets.OPEN_PAYMENTS_SERVER_URL }}
        OPEN_PAYMENTS_WALLET_ADDRESS: ${{ secrets.OPEN_PAYMENTS_WALLET_ADDRESS }}
        OPEN_PAYMENTS_KEY_ID: ${{ secrets.OPEN_PAYMENTS_KEY_ID }}
        OPEN_PAYMENTS_PRIVATE_KEY_PATH: ./private.key

    - name: Build with snippets feature
      run: cargo build --features snippets

  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Build docs
      run: cargo doc --no-deps --features snippets 